# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BBSampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BBSampleApp

    pod 'AFNetworking'
    pod 'TTTAttributedLabel'
    pod 'JMImageCache'
    pod 'ICViewPager'
    pod 'Fabric'
    pod 'TwitterKit'
    pod 'TwitterCore'
    pod 'KeychainItemWrapper'
    pod 'Crashlytics'
    pod 'AppDynamicsAgent'
    pod 'CardIO'

    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    ]


  target 'BBSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BBSampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
